const $=s=>document.querySelector(s),worker=new Worker('./worker.js',{type:'module'});let ready=false,request=0,timer,result;
const paths=['001-backyard-propane-compact.md','002-induction-modular-small-repair.md'];
function calculate(){request++;clearTimeout(timer);$('#participation-value').textContent=`${Number($('#participation').value).toFixed(1)}%`;$('#wage-value').textContent=`$${Number($('#wage').value).toLocaleString('en-US')}`;$('#catalog-link').href=`https://github.com/giodl73-repo/CERES/blob/main/catalog/smithing/entries/${paths[Number($('#entry').value)]}`;if(!ready)return;$('#export').disabled=true;$('#status').textContent='Evaluating…';timer=setTimeout(()=>worker.postMessage({id:request,entry:Number($('#entry').value),scale:$('#scale').value,participation:Number($('#participation').value)/100,wage:Number($('#wage').value)}),80);}
function fail(message){$('#status').textContent=message;$('#lenses').replaceChildren();$('#export').disabled=true;}
worker.onerror=()=>fail('Evaluator could not load. Reload to retry or read the catalog.');
worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;document.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);calculate();return;}if(data.id!==undefined&&data.id!==request)return;if(data.type==='error'){fail(ready?data.message:'Evaluator could not load. Reload to retry or read the catalog.');return;}result=data.result;$('#lenses').replaceChildren();for(const [key,name,label]of [['market','Market','years to recover capital'],['coop','Co-op','break-even members'],['civic','Civic','annual cost per household']]){const lens=result[key],section=document.createElement('article');section.className='lens';section.id=key;const title=document.createElement('h3');title.textContent=name;const verdict=document.createElement('span');verdict.className='badge';verdict.textContent=lens.verdict;title.append(verdict);const metric=document.createElement('strong');metric.textContent=lens.primary_metric<0?'Not recoverable':key==='civic'?`$${lens.primary_metric.toFixed(2)}`:lens.primary_metric.toLocaleString('en-US',{maximumFractionDigits:2});const explanation=document.createElement('p');explanation.textContent=label;const notes=document.createElement('p');notes.textContent=lens.notes.replaceAll('feasible_pool=','Potential members: ').replaceAll('break_even=','break-even members: ').replaceAll('total_annual_cost=','annual cost: $').replaceAll('per_hh=','Annual cost per household: $').replaceAll('threshold=','threshold: ').replaceAll('hrs/capita=','hours per person: ').replaceAll('wage_verdict=','Income test: ').replaceAll('payback_verdict=','payback test: ').replaceAll('take_home=','take-home: $').replaceAll('payback=','payback: ').replaceAll(' vs median=',' against median wage $').replaceAll('annual_gross_margin <= 0; payback never recoverable','Annual margin is nonpositive; capital cannot be recovered').replaceAll('market_price_per_unit absent or zero; entry not designed for market lens','No market selling price is available for this design')||'Both market tests meet the model’s favorable thresholds.';section.append(title,metric,explanation,notes);$('#lenses').append(section);}$('#population').textContent=`${result.population.toLocaleString('en-US')} people · ${result.households.toLocaleString('en-US')} households · draft catalog sensitivity`;$('#status').textContent=`Evaluated in ${data.ms.toFixed(1)} ms · processing stays on your device`;$('#export').disabled=false;};
for(const id of ['participation','wage'])$(`#${id}`).oninput=calculate;for(const id of ['entry','scale'])$(`#${id}`).onchange=calculate;
$('#reset').onclick=()=>{$('#entry').value='0';$('#scale').value='town';$('#participation').value='2.5';$('#wage').value='56000';history.replaceState(null,'',location.pathname);calculate();};
$('#share').onclick=async()=>{const url=new URL(location.href);url.search='';for(const id of ['entry','scale','participation','wage'])url.searchParams.set(id,$(`#${id}`).value);history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);}catch{}$('#status').textContent='Scenario link is in the address bar.';};
$('#export').onclick=()=>{if(!result)return;const inputs=Object.fromEntries(['entry','scale','participation','wage'].map(id=>[id,$(`#${id}`).value]));const url=URL.createObjectURL(new Blob([JSON.stringify({inputs,result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ceres-draft-evaluation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const params=new URLSearchParams(location.search);for(const[id,min,max,step]of [['entry',0,1,1],['participation',0.1,20,0.1],['wage',10000,200000,1000]]){const n=Number(params.get(id));if(params.has(id)&&Number.isFinite(n)&&n>=min&&n<=max&&Math.abs(n/step-Math.round(n/step))<1e-8)$(`#${id}`).value=n;}if(['village','town','small_city'].includes(params.get('scale')))$('#scale').value=params.get('scale');worker.postMessage({type:'init'});
